### PR TITLE
fix problem with escaping zero and other control characters

### PR DESCRIPTION
**Pull request by andreashofer123**
Hello Enrico,

First of all, thank you for having created the inspect module. It is of great use for me.

Here I have a fix for a bug that shows up when you have zero characters in the string.

Best regards 
Andreas Hofer

### CODE REVIEW

**Comment by kikito** [comment]
Hi, thanks for the 3 PRs and sorry it took me a while to answer back.

Two comments:
* I suspect that there is no need to use two different variables - `controlCharsTranslationBeforeDigit` & `controlCharsTranslation`. Can you try to simplify that code a bit, maybe using a single table?
* It seems that this needs some more tests than just the Zero char. Please add them too.

**Comment by andreashofer123** [comment]
Sorry for misspelling your name.

The problem comes from the way that escapes with digits \ddd are handled. From the manual:

> (Note that if a decimal escape sequence is to be followed by a digit, it must be expressed using exactly three digits.)

So in principle, we could just always insert three digits \000. This would be the simplest solution to get rid of the additional gsub, but it is not nice to the eye, however. 

Please note that we already have five scans through the string. Three done by 'smartQuote' and two by 'escape'. Now I added one more. If efficiency is of concern, we should take measurements and find a different solution for formatting the strings.

**Comment by kikito** [comment]
Thanks for the explanation. I need a bit of time to think about this. I'll get back to you on this in a couple days.

**Comment by kikito** [comment]
I'm sorry, I still don't understand fully how this works.

Here's my analysis so far:

* `controlCharsTranslation` contains "usual human-friendly" escapes for ascii codes. For example, the character number 10 gets transformed into a backslash followed by `n` (`"\\n"`). For the ones which don't have a "usual" translation, it contains a slash followed by a two digit code - so character `0` becomes `"\\00"`.
* `controlCharsTranslationBeforeDigit` contains a three-digit version of the table. The caracter `0` becomes `"\\000"`. The "characters with a especial escape sequence", such as `\n`, are not on this list.

The algorithm you implemented does the following:

* First, transform all backslashes into double backslashes.
* Then, detect all **control codes followed by 1 digit (?)** (pattern: `"(%c)%f[0-9]"`) and transform that using `controlCharsTranslationBeforeDigit`. So if there is a character `0` followed by any number, that zero char will become `"\\000"`s.
* Then, detect all **control codes (not followed by a digit this time)** (pattern: `"(%c)"`) and transform that using `controlCharsTranslation`. So char `10` becomes `"\\n"`.

I understand the first step, and the last one. The one in the middle, however ... I don't understand what's doing, or why.

> So in principle, we could just always insert three digits \000. This would be the simplest solution to get rid of the additional gsub, but it is not nice to the eye, however.

The way I see this is: very few people will need to inspect control chars. For those that do, I am willing to "make them suffer a bit" and always see 3-digit escapes, if that makes the code simpler (and faster, but that's secondary). Otherwise *I* am the one suffering, having to maintain a code which I struggle to understand fully.

**Comment by andreashofer123** [comment]
For displaying the control chars I tried to follow the Lua way of encoding them, that means writing the string the same way as in Lua source code. 

The understand the problem I tried to solve with the control character let me give an example. Assume we write this string in a Lua program: `"a\1b"`. The Lua compiler sees the backslash followed by a digit, so it scans the digits until it comes to the `b` and then it will encode the character as `\1`. Similar for `"a\12b"` where it scans both digits. It will never scan more than three digits, because `\255` is the highest number that can appear in a byte. Lets assume I want to write a string with a control character followed by a digit. Simply `"a\19"` will not work, because the compiler scans all the digits. So in this case I will have to write `"a\0019"` so that the control character is finished after three digits and the `9` does not belong to it.

The algorithm I made encodes the control characters with three digits if necessary, and with one or two digits otherwise.

According to the above rule, always encoding control characters with three digits is a simple solution that will always work. In that case you can simply fill `controlCharsTranslation` with the `\000` variant and remove `controlCharsTranslationBeforeDigit` entirely.

If you think this would be the better solution, then by all means use this one. This is your project. I can always keep the other variant in my private fork when I am not willing to 'suffer a bit' :-) .

**Comment by kikito** [comment]
Thanks for taking the time to explain the situation to me.

After meditating about this during the weekend, and comparing both options (always 3 digits vs sometimes 1 or 2 digits in the escapes) I have decided to merge your version (with some minor tweaks in the specs / names).

Will release new version soon. Thanks again!

**Pull request merged**
